# Generated by Django 2.1 on 2019-05-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='computer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapps.Computer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_date',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_date',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
