# Generated by Django 2.1 on 2019-05-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapps', '0003_auto_20190527_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.CharField(max_length=255),
        ),
    ]
