# Generated by Django 2.1 on 2019-05-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapps', '0004_auto_20190527_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
